<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>1.2.0</Version>
    <Authors>Victor Gomez</Authors>
    <Copyright>Copyright © Victor Gomez</Copyright>
  </PropertyGroup>

</Project>
